services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: travel-package-proposal-db
  test-db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: travel-package-proposal-db
  redis:
    image: redis
    ports:
      - "6379:6379"
  test-redis:
    image: redis
    ports:
      - "6380:6379"
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
#  rabbitmq:
#    image: rabbitmq:3-management
#    healthcheck:
#      test: rabbitmq-diagnostics -q ping
#      interval: 30s
#      timeout: 30s
#      retries: 3