services:
  iam:
    build:
      context: .
      dockerfile: ./apps/iam/Dockerfile
      target: development
    command: npm run start:dev iam
    env_file:
      - ./apps/iam/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: travel-package-proposal-db
  redis:
    image: redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  # E2e/integration tests
#  test-postgres:
#    image: postgres
#    ports:
#      - "5433:5432"
#    environment:
#      POSTGRES_PASSWORD: pass123
#      POSTGRES_DB: travel-package-proposal-db
#  test-redis:
#    image: redis
#    ports:
#      - "6380:6379"
