apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iam
  name: iam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '3001'
    spec:
      containers:
      - image: carlosmoliveira/iam
        name: iam
        ports:
          - containerPort: 3001
        env:
          - name: RABBITMQ_URI
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: connectionUri
          - name: PORT
            value: '3001'
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: connectionUri
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt
                key: jwtSecret
          - name: JWT_TOKEN_AUDIENCE
            value: 'localhost:3000'
          - name: JWT_TOKEN_ISSUER
            value: 'localhost:3000'
          - name: ACCESS_TOKEN_TTL
            value: '3600'
          - name: REFRESH_TOKEN_TTL
            value: '86400'
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: redis
                key: host
          - name: REDIS_PORT
            value: '15428'
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
          - name: REDIS_USERNAME
            value: 'default'
        imagePullPolicy: Always

#      imagePullSecrets:
#        - name: fcregcred