apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iam
  name: iam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
    spec:
      containers:
      - image: carlosmoliveira/iam
        name: iam
        ports:
          - containerPort: 3001
        env:
          - name: RABBITMQ_URI
            value: 'amqp://rabbitmq:5672'
          - name: PORT
            value: '3001'
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: connectionUrl
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt
                key: jwtSecret
          - name: JWT_TOKEN_AUDIENCE
            value: 'localhost:3000'
          - name: JWT_TOKEN_ISSUER
            value: 'localhost:3000'
          - name: ACCESS_TOKEN_TTL
            value: '3600'
          - name: REFRESH_TOKEN_TTL
            value: '86400'
          - name: REDIS_HOST
            value: 'redis'
          - name: REDIS_PORT
            value: '6379'



#      imagePullSecrets:
#        - name: fcregcred