apiVersion: v1
kind: Service
metadata:
  labels:
    app: iam
  name: iam
spec:
  ports:
    - name: 'http'
      protocol: TCP
      port: 3001
      targetPort: 3001
  selector:
    app: iam
  type: NodePort
