services:
  test-db:
    image: postgres
    ports:
      - "5440:5432"
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: iam-db
  test-redis:
    image: redis
    ports:
      - "6380:6379"