apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - image: carlosmoliveira/payment
        name: payment
        env:
          - name: PORT
            value: '3004'
          - name: RABBITMQ_URI
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: connectionUri
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: stripe
                key: secretKey
          - name: STRIPE_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: stripe
                key: webhookSecretKey
          - name: STRIPE_CHECKOUT_SUCCESS_URL
            value: 'https://localhost:3001/payments/checkout'
          - name: STRIPE_CHECKOUT_CANCEL_URL
            value: 'https://localhost:3001/payments/cancel'