prometheus:
  global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
  alerting:
    alertmanagers:
      - static_configs:
          - targets: []
        scheme: http
        timeout: 10s
        api_version: v2
  scrape_configs:
    # Scrape Prometheus
    - job_name: prometheus
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
        - targets:
            - travel-package-proposal-prometheus-server:80
    # Scrape IAM Microservice
    - job_name: iam
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
        - targets:
            - iam:3001

grafana:
  service:
    type: NodePort
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://travel-package-proposal-prometheus-server:80
        isDefault: true
        access: proxy
        editable: true